### ISSUE TITLE
PHP 8 dependence

### ISSUE THREAD

**Issue by pomor** [LM-Commons/LmcAdmin#7]
current version is ^7.3

**Comment by ALTAMASH80** [comment]
Thanks for the update. I'll check it for PHP version 8.* as well.

**Comment by pomor** [comment]
It was tested under 8.0 with --ignore-platform-reqs,  working without complication.

**Comment by ALTAMASH80** [comment]
Added PHP 8 version as well. I hope it will be good for now. I'll close this issue on Monday, Jan 24 2022, if no further comment is found. Thanks!
